#!/usr/bin/env bash
# 配布物に含まれる依存ライブラリのライセンスを THIRD-PARTY-NOTICES.txt に書き出す。
# `pnpm notices` から呼ばれる。依存を足したり上げたりしたら流し直してコミットする
# (lib.rs のテストが、直接依存がこのファイルに載っているかを見る)。
#
# Rust 側は cargo-about (`cargo install cargo-about --locked --features cli`)、
# 設定は src-tauri/about.toml、書式は src-tauri/about.hbs。
# npm 側は package.json の dependencies に、BUNDLED_RUNTIME に並べた package を足して
# node_modules から読む。devDependencies は基本的に配布物に入らないが、SvelteKit では
# svelte / @sveltejs/kit が devDependencies のまま runtime として bundle される。
# `vite build --sourcemap true` の sourcemap に出てくる node_modules を調べた結果
# (2026-09-28) の差分が svelte / @sveltejs/kit / esm-env (両者の依存) で、それを
# BUNDLED_RUNTIME に列挙している。フロントの依存を大きく変えた時は同じ方法で調べ直す。
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD-PARTY-NOTICES.txt"

if ! cargo about --version >/dev/null 2>&1; then
  echo "Error: cargo-about is not installed. Run: cargo install cargo-about --locked --features cli" >&2
  exit 1
fi
if [ ! -d node_modules ]; then
  echo "Error: node_modules is missing. Run: pnpm install" >&2
  exit 1
fi

# 同じディレクトリに作る。別ファイルシステムの /tmp からの mv はコピーになり、途中で
# 止まると壊れた出力が残る
TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP"' EXIT

{
  cat <<'HEADER'
THIRD-PARTY NOTICES

ArcVault bundles the open source libraries listed below. Each entry gives the
license, the packages it applies to, and the license text as shipped by the
package. Generated by scripts/generate-third-party-notices.sh; do not edit by hand.

################################################################################
# JavaScript packages (bundled into the web view)
################################################################################

HEADER

  node - <<'NODE'
const fs = require("fs");
const path = require("path");
// devDependencies のまま bundle される runtime。[名前, 探し始める package] で、
// 直下の node_modules に無い推移依存 (esm-env) は、それを使う package の隣から引く
// (pnpm は依存を `.pnpm/<pkg>@<ver>/node_modules/` に並べる)。
const BUNDLED_RUNTIME = [
  ["svelte", null],
  ["@sveltejs/kit", null],
  ["esm-env", "svelte"],
];
const packageDir = (name, from) => {
  if (!from) return fs.realpathSync(path.join("node_modules", name));
  const fromDir = fs.realpathSync(path.join("node_modules", from));
  // fromDir は .pnpm/<pkg>@<ver>/node_modules/<from> (scope 付きなら 1 段深い)
  const depth = from.startsWith("@") ? 2 : 1;
  let base = fromDir;
  for (let i = 0; i < depth; i++) base = path.dirname(base);
  return path.join(base, name);
};
const deps = Object.keys(JSON.parse(fs.readFileSync("package.json", "utf8")).dependencies)
  .map((name) => [name, null])
  .concat(BUNDLED_RUNTIME)
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
for (const [name, from] of deps) {
  const dir = packageDir(name, from);
  const pkg = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
  const repo = typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url;
  // LICENSE.spdx のような SPDX のメタデータは本文ではないので除く
  const files = fs
    .readdirSync(dir)
    .filter((f) => /^(LICEN[CS]E|COPYING|NOTICE)/i.test(f) && !/\.spdx$/i.test(f))
    .sort();
  console.log("=".repeat(80));
  console.log(`License: ${pkg.license}`);
  console.log("");
  console.log("Used by:");
  console.log(`  ${name} ${pkg.version}${repo ? ` (${repo})` : ""}`);
  console.log("");
  if (files.length === 0) {
    // 本文が同梱されていない package。表記と配布元だけ残す
    console.log("The package does not ship its license text; see the repository above.");
    console.log("");
    continue;
  }
  for (const f of files) {
    if (files.length > 1) console.log(`--- ${f} ---`);
    console.log(fs.readFileSync(path.join(dir, f), "utf8").replace(/\s+$/, ""));
    console.log("");
  }
}
NODE

  cat <<'HEADER'
################################################################################
# Rust crates (compiled into the binary)
################################################################################

HEADER

  # --fail: ライセンスを特定できない crate があれば警告で省略せず失敗させる
  cargo about generate --manifest-path src-tauri/Cargo.toml --locked --fail src-tauri/about.hbs
} > "$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
